### ISSUE TITLE
Text Encoder and Image Encoder Using Different Latent Space

### ISSUE THREAD

**Issue by franperic** [alexcg1/jina-meme-search#7]
In this showcase, the images are embedded using the Clip model. But the text is embedded using a SpaCy Encoder. Why are you not using the ClipTextEncoder?

I tried to switch to ClipTextEncoder. But I am receiving the error below. Seems to be a problem with the PQliteIndexer.

```
meme_text_indexer@853[E]:AssertionError()
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 226, in _handle
    peapod_name=self.name,
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 171, in handle
    field='groundtruths',
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/jina/executors/__init__.py", line 200, in __call__
    self, **kwargs
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/jina/executors/decorators.py", line 106, in arg_wrapper
    return fn(*args, **kwargs)
  File "/home/fran_peric/.jina/hub-packages/pn1qofsj/executor.py", line 97, in index
    self._index.index(flat_docs)
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/pqlite/index.py", line 171, in index
    n_data, _ = self._sanity_check(x)
  File "/home/fran_peric/jina-demo/lib/python3.7/site-packages/pqlite/index.py", line 122, in _sanity_check
    assert x.shape[1] == self.dim
AssertionError
```

**Comment by franperic** [comment]
No need to align the latent space of the image and text embeddings.
This showcase is not really cross-modal. The text queries are used with the meme captions. So SpaCy Encoder is fine in this case.

**Comment by alexcg1** [comment]
I'm using SpaCy specifically because it indexed like 200k memes in 4 minutes on my laptop. sentence-transformers was chugging away for hours and hours. I never tried CLIPTextEncoder because (as you discovered), the cross-modality is a lie :laughing: Therefore, no reason to go with it.

For image encoding, I wrote a few [blog posts](http://blog.alexcg.net/) that may be of interest, comparing encoders
